name: Pylint

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/pylint.yml'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip pylint

      - name: Analyse code with pylint
        run: |
          # Проверяем каталоги src/ и tests/
          pylint src tests | tee pylint-report.txt

      - name: Upload pylint report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt
